FROM python:3.11.11-slim

ENV TZ=Europe/Berlin

RUN pip install numpy
RUN pip install scipy
RUN pip install matplotlib
RUN pip install gymnasium
RUN pip install joblib
RUN pip install stable-baselines3